### ISSUE TITLE
Tracking of SGX patch migration

### ISSUE THREAD

**Issue by berendt** [osism/issues#750]
- [x] https://github.com/intel/secured-cloud-management-stack/blob/main/nova-intel-sgx.patch (https://github.com/openstack/nova)
- [x] https://github.com/intel/secured-cloud-management-stack/blob/main/python-novaclient-intel-sgx.patch (https://github.com/openstack/python-novaclient)
- [x] https://github.com/intel/secured-cloud-management-stack/blob/main/python-openstackclient-intel-sgx.patch (https://github.com/openstack/python-openstackclient)

Technical tracking issue for https://github.com/SovereignCloudStack/issues/issues/246.

**Comment by gndrmnn** [comment]
https://github.com/openstack/python-openstackclient

[python-openstackclient-intel-sgx.txt](https://github.com/osism/issues/files/13334150/python-openstackclient-intel-sgx.txt)

**Comment by gndrmnn** [comment]
https://github.com/openstack/python-novaclient

[python-novaclient-intel-sgx.txt](https://github.com/osism/issues/files/13334283/python-novaclient-intel-sgx.txt)

**Comment by gndrmnn** [comment]
https://github.com/openstack/nova

[nova-intel-sgx.txt](https://github.com/osism/issues/files/13379494/nova-intel-sgx.txt)

**Comment by gndrmnn** [comment]
https://github.com/openstack/diskimage-builder

[dib-intel-sgx.txt](https://github.com/osism/issues/files/13439968/dib-intel-sgx.txt)

**Comment by berendt** [comment]
Closing this as done. We’ll proceed with new issues after the OpenInfra Days in Berlin + Paris.
